//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scalodrom
{
    using System;
    using System.Collections.Generic;
    
    public partial class grapple_series
    {
        public long id { get; set; }
        public long id_training { get; set; }
        public long track_num { get; set; }
        public long row_num { get; set; }
        public long grapple_num { get; set; }
    
        public virtual training training { get; set; }
    }
}
