//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scalodrom
{
    using System;
    using System.Collections.Generic;
    
    public partial class light_intensity_series
    {
        public long id { get; set; }
        public long id_training { get; set; }
        public long order { get; set; }
        public long duration { get; set; }
        public long intensity { get; set; }
    
        public virtual training training { get; set; }
    }
}
