//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scalodrom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class project_dbEntities1 : DbContext
    {
        public project_dbEntities1()
            : base("name=project_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<trainee> trainee { get; set; }
        public virtual DbSet<tr_path> tr_path { get; set; }
        public virtual DbSet<training> training { get; set; }
        public virtual DbSet<angle_series> angle_series { get; set; }
        public virtual DbSet<grapple_series> grapple_series { get; set; }
    }
}
