//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scalodrom
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainee
    {
        public long id { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string birthdate { get; set; }
        public string create_date { get; set; }
        public long id_user_create { get; set; }
        public Nullable<long> id_user_modified { get; set; }
        public string modified_date { get; set; }
        public string fullname { get; set; }
    
        public virtual login login { get; set; }
        public virtual login login1 { get; set; }
    }
}
